server:
  port: 8000
  forward-headers-strategy: ${FORWARD-HEADER-STRATEGY:NATIVE}
gateway:
  #Valid values are guava(for local), redis
  cacheMethod: ${CACHE_METHOD:guava}
  redis:
    #Will not be used if cacheMethod is guava
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:password}
    expiry: ${REDIS_KEY_EXPIRY:5}
    rootNamespace: ${ROOT_NAMESPACE:gateway}
    keep-alive-enabled: ${KEEP_ALIVE_ENABLED:false}
    retry: ${REDIS_RETRY:0}
  serviceoptions:
    timeout: ${SERVICE_TIMEOUT:5}
    responseMaxRetryAttempts: ${RESPONSE_MAX_RETRY_ATTEMPTS:2}
  db:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT:5432}
    schema: ${GATEWAY_DB_NAME}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    poolSize: ${POOL_SIZE:5}
    replica-read-enabled: {REPLICA_READ_ENABLED:false}
    replica:
      host: ${REPLICA_POSTGRES_HOST}
      port: ${REPLICA_POSTGRES_PORT:5432}
      user: ${REPLICA_POSTGRES_USER}
      password: ${REPLICA_POSTGRES_PASSWORD}
      poolSize: ${REPLICA_POOL_SIZE:3}
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
identity:
  clientId: ${GATEWAY_CLIENT_ID}
  clientSecret: ${GATEWAY_CLIENT_SECRET}
  url: ${KEYCLOAK_URL}
  realm: ${REALM}
  host: ${GATEWAY_HOST}
  userName: ${GATEWAY_ADMIN_USER}
  password: ${GATEWAY_ADMIN_PASSWORD}
  access-token-expiry-in-minutes: ${TOKEN_EXPIRY:2}
webclient:
  use-connection-pool: ${USE_HTTP_CONNECTION_POOL:true}
  connection-pool:
    poolSize: ${HTTP_CONNECTION_POOL_SIZE:500}
    maxLifeTime: ${HTTP_CONNECTION_MAX_LIFETIME:10}
    maxIdleTimeout: ${HTTP_CONNECTION_MAX_IDLETIME:5}