server:
  port: 8000
gateway:
  #Valid values are guava(for local), redis
  cacheMethod: ${CACHE_METHOD:guava}
  redis:
    #Will not be used if cacheMethod is guava
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  # timeout in seconds
  serviceoptions:
    timeout: ${SERVICE_TIMEOUT:5}
    registryPath: ${REGISTRY_PATH:registry-local.yaml}
    responseMaxRetryAttempts: ${RESPONSE_MAX_RETRY_ATTEMPTS:2}
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
clientregistry:
  clientId: ${GATEWAY_CLIENT_ID}
  clientSecret: ${GATEWAY_CLIENT_SECRET}
  url: ${CENTRAL_REGISTRY_URL}
  jwkUrl: ${CENTRAL_REGISTRY_JWK_URL}
