server:
  port: 8004
gateway:
  #Valid values are guava(for local), redis
  cacheMethod: ${CACHE_METHOD:guava}
  redis:
    #Will not be used if cacheMethod is guava
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  # timeout in seconds
  serviceoptions:
    timeout: 50
    registryPath: ${REGISTRY_PATH:registry-local.yaml}
clientregistry:
  clientId: gateway
  clientSecret: 29868f71-ee62-45c6-9c42-f5ecf8bb9179
  url: http://localhost:8080
  jwkUrl: http://localhost:8080/certs
