server:
  port: 8000
gateway:
  #Valid values are guava(for local), redis
  cacheMethod: ${CACHE_METHOD:guava}
  redis:
    #Will not be used if cacheMethod is guava
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
    expiry: ${REDIS_KEY_EXPIRY}
  # timeout in seconds
  serviceoptions:
    timeout: ${SERVICE_TIMEOUT:5}
    registryPath: ${REGISTRY_PATH:registry-local.yaml}
    responseMaxRetryAttempts: ${RESPONSE_MAX_RETRY_ATTEMPTS:2}
  db:
    host: ${POSTGRES_HOST}
    port: 5432
    schema: ${GATEWAY_DB_NAME}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    poolSize: 5
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
identity:
  clientId: ${GATEWAY_CLIENT_ID}
  clientSecret: ${GATEWAY_CLIENT_SECRET}
  url: ${KEYCLOAK_URL}
  realm: ${REALM}
  host: ${GATEWAY_HOST}
webclient:
  keepAlive: ${GATEWAY_KEEP_ALIVE:true}